# Site settings
title: Robin | Google Drive Empty Trash
description: "Google Drive Empty Trash"
url: "https://robinli.github.io/GoogleDriveEmptyTrash"
author:
  name: "Robin Li"
  email: "im@robinks.net"
  url: "http://www.jacoporabolini.com"

# Build settings
baseurl: /GoogleDriveEmptyTrash/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
